### PR TITLE
Form validation

### PR DESCRIPTION
**Pull request by Nessrine88**
Hello,

This pull request adds a lowercase validation for the email input field in the form. It ensures that the entered email is in lowercase before allowing the form submission.

Changes Made:
- Modified the JavaScript code to compare the email input value with its lowercase value.
- If the input value contains any uppercase characters, the form submission is prevented and an error message is displayed.
- If the input value is in all lowercase, the form is successfully submitted.
Testing Done:
- Tested the form with different email inputs, including uppercase and lowercase characters.
- Verified that the form submission is prevented when uppercase characters are present and successfully submitted when all characters are lowercase.

Please review  this pull request. Thank you!

### CODE REVIEW

**Review by Ofarouq310 — COMMENTED** [review]
Hi @Nessrine88 & @jovasal, ✋  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## 🔴 Invalid Code Review Request

- You have submitted a project, that is missing the JavaScript linters `ESlint`.

- Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Nessrine88** [comment]
Hi, @Ofarouq310 
"I believe there might be a mistake because the ESLint rules seem to be properly configured. I kindly request you to double-check and verify it again."
image

**Comment by Ofarouq310** [comment]
Hey @Nessrine88,

Kindly note that what is in your screenshot is the `node_modules` checker, if the `ESlint` was installed, you would have 5 checks rather than 4 as you see in the next screenshot. 
I will invalidate your project once again, kindly install the linters properly.

  image

**Review by emmanuellekamwa — APPROVED** [review]
**STATUS: APPROVED 🍾✔🎉**
Hello @Nessrine88 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Descriptive PR.
- Good commit messages.
- Correct git-flow.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
